### ISSUE TITLE
I am a student,Could you help me solving this peblem?

### ISSUE THREAD

**Issue by Jsondp** [viscom-ulm/MCCNN#4]
Hi,author,what is the "MCConv.so"?where I can find it?

**Comment by phermosilla** [comment]
Hello, MCConv.so is the compiled library which contains the new operations for Tensorflow. In order to obtain this file, you have to compile the files in the folder tf_ops. You can compile them following the instructions here: https://github.com/viscom-ulm/MCCNN#compiling-tensorflow-operations
