### ISSUE TITLE
Compling MCConv.so

### ISSUE THREAD

**Issue by ninaqy** [viscom-ulm/MCCNN#5]
Hi, may I ask your setting for the tf_ops compling? I followed your suggestion by using tensorflow-gpu=1.5.0 and python=2.7. Besides, I use cuda=9.0, gcc=4.8.5. Currently the MCConv.so can successfully compiled by your provided script generated by genCompileScript.py. 

However, running "python ModelNet.py  --grow 128 --useDropOut " inside ModelNet results in error: tensorflow.python.framework.errors_impl.NotFoundError: /home/user/MCCNN/tf_ops/MCConv.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumE

It seems the compiling encounter some issues. Could you provide your CUDA and GCC setting in order to follow your environment setting?

**Comment by phermosilla** [comment]
Hello, It seems that the configuration is correct. Did you try to change the script as described int he README to -D_GLIBCXX_USE_CXX11_ABI=1? You could also try to use a new gcc compiler. Let me know your progress on that.

**Comment by ninaqy** [comment]
Thank you for your prompt reply!

Yes, I have tried the suggestion in your readme, i.e. change -D_GLIBCXX_USE_CXX11_ABI=1, however, the problem still remains. It can be compiled but the ModelNet.py reports same bug.

You mentioned a new gcc compiler, may I ask which version do you use for this project?

**Comment by phermosilla** [comment]
The problem I think is with a mismatch between the compiler/compiler properties used for compiling vs runtime. I can tell you the configuration we are currently using here. We are using here tensorflow 1.11, cuda 9.0, and gcc/g++ 6. Maybe you can try this configuration.

**Comment by ninaqy** [comment]
Thanks, I will follow your settings. Report to you if further problem occurs!
