### ISSUE TITLE
Error in sess.run:  an illegal memory access

### ISSUE THREAD

**Issue by haoyu6427** [viscom-ulm/MCCNN#6]
Hi, could you please help me solve this problem. I tried to run the ShapeNet. After loading data and creating network, when session begin to run, I encountered a problem:

GPUassert: an illegal memory access was encountered poisson_sampling.cu 200
GPUassert: an illegal memory access was encountered find_neighbors.cu 299
Segmentation fault (core dumped)

I'd appreciate it if you could provide some information about how to solve this problem. Thanks.

**Comment by phermosilla** [comment]
Hello, thanks for showing interest in our work. My first guess is that you are running out of GPU memory. Which GPU are you using and which command are you executing? Best

**Comment by haoyu6427** [comment]
Thank you for you reply!
I'm using the Tesla K80. I tried the command: python ShapeNet.py。
I'm sure my GPU have enough memory: at least 11GB.
Could you share the download script of dataset with me?
Thank you very much!

**Comment by phermosilla** [comment]
Try to run the script without any parameter:

python ShapeNet.py 

If you still have the same error I imagine there will be some problem with the data.
